### ISSUE TITLE
AssertionError: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by samicrusader** [samicrusader/Histoire#3]
Using `hypercorn app` to launch Histoire instead of using the server called when `__name__` is `__main__` (`python3 app.py`) leads tasks running in a ProcessPool (used for CPU-bound tasks) to crash with an AssertionError: "`daemonic processes are not allowed to have children`".

The current solution is to not use Hypercorn directly, but to use the server called inside the app, but this is a hack and needs to be fixed somehow.

**Comment by samicrusader** [comment]
this appears to have been fixed in some commit that i dont know about

**Comment by konstantin-baidin-y42** [comment]
Hey @samicrusader I'm solving the same issue right now. I need to use ProcessPoolExecutor in the web app running by hypercorn. And I'm getting `daemonic processes are not allowed to have children`. Can you recall how you fixed this?
Thank you.

**Comment by samicrusader** [comment]
@konstantin-baidin-y42 i honestly think i just started calling Hypercorn in app.py directly to solve that issue since i'm still using ProcessPoolExecutor in `thumbnailer()`
https://github.com/samicrusader/Histoire/blob/master/app.py#L546-L566

**Comment by konstantin-baidin-y42** [comment]
thank you for sharing. I just switched to uvicorn 😄 , in my case the exact application server doesn't matter much
